### ISSUE TITLE
Async route and component definition

### ISSUE THREAD

**Issue by michalkvasnicak** [michalkvasnicak/routex#1]
Add possibility to load route in async.

Add prop to `Link` component to call transitionTo with given path (and parse query params from string).
Link should not generate link for this definition of route.

**Comment by michalkvasnicak** [comment]
Link should throw error if we are generating URL for named route but this route is not defined (can be async)?

**Comment by michalkvasnicak** [comment]
Or we can use something like absolute route name `index.child.child.about` and if something between it isn't registered, tries to load in async?

But how will server know when rendering finished? Propably ignore it on server side?

**Comment by gaearon** [comment]
To be honest I think React Router was right in dropping support for named routes. They don't add much value anyway, and they make it easy to break URLs (which you shouldn't do for the sake of your users). Plus it's easy to implement named URLs *on top* of the router by just writing your own functions.

**Comment by michalkvasnicak** [comment]
Yeah I agree with you and I'm removing route names. `transitionTo` action is accepting path anyway, so it was only little "helper" to not write URLs by hand.

**Comment by michalkvasnicak** [comment]
It is possible now to define async routes or components. It just needs to be a function returning a Promise.
