### ISSUE TITLE
typo in createRoutex

### ISSUE THREAD

**Issue by sylvaingi** [michalkvasnicak/routex#13]
nextRoute never ends up in routex state: https://github.com/michalkvasnicak/routex/blob/master/src/createRoutex.js#L87

**Comment by michalkvasnicak** [comment]
Is this really a typo? Because transitioning is started when router starts transitioning using `run`. So in case when router is transitioning it should be filled with route you are resolving but after transition is finished it is removed because there is no next route until you run a new transition.

**Comment by sylvaingi** [comment]
What I meant is that when routex state is `TRANSITIONING`, `nextRoute` should refer to the route being resolved (`action.nextRoute`). It is not the case right now, in fact `action.route === state.route`.

**Comment by michalkvasnicak** [comment]
Ah I see, I am sorry :) I did not understand. I'll take a look.

**Comment by michalkvasnicak** [comment]
This is strange. I added test for it and it passed. Aren't you trying to resolve against same path?

**Comment by sylvaingi** [comment]
The problem is not in `Router` but in the reducer, at the line pointed in the OP. Routing works fine so far.

When the reducer handles the action `ROUTE_CHANGE_START`, it does not store the correct `nextRoute`, the one that was resolved, it puts the current one instead.

If it's still unclear I'll send a PR with a test case, hopefully it'll be clearer than my semi-broken english :)

**Comment by michalkvasnicak** [comment]
I think it'd be better to have test for that :) It will help with future modifications. Please, can you write a test for that?

I think I should write createRoutex test because it is empty now.

**Comment by sylvaingi** [comment]
Sure, I'll have a look at it this evening.

**Comment by michalkvasnicak** [comment]
I am sorry, you don't need to :) I will write whole test for createRoutex and fix this typo for now. I must have been tired or what when I didn't understand a problem here in a first place. :)

**Comment by sylvaingi** [comment]
That's fine, it's a minor issue that does not impact anything yet. I'm not
even sure if I would need it, maybe for some middleware ensuring protected
routes are not accessed without a logged in state.

On Mon, Jul 27, 2015 at 11:00 AM Michal Kvasničák <notifications@github.com>
wrote:

> I am sorry, you don't need to :) I will write whole test for createRoutex
> and fix this typo for now. I must have been tired or what when I didn't
> understand a problem here in a first place. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michalkvasnicak/routex/issues/13#issuecomment-125134929>
> .
>
-- 

Sylvain
