### ISSUE TITLE
Take a look at rackt/history

### ISSUE THREAD

**Issue by gaearon** [michalkvasnicak/routex#6]
I know @mjackson is re-implementing the router primitives (such as histories) in a more functional way in https://github.com/rackt/history. While this is a work in progress, you might be interested to take a look and maybe even use it internally.

**Comment by michalkvasnicak** [comment]
Thank you, I saw that you starred it and I'm planning to take a look and maybe replace my "naive" histories. I was hoping he will release it as a standalone package.

**Comment by michalkvasnicak** [comment]
I have this almost finished. Just need to make some PR and tests to rackt-history because I found some bugs.

**Comment by michalkvasnicak** [comment]
Finished but it's just an experiment. Needs ract-history to be at least in state when it is published to npm.
