### ISSUE TITLE
Initial state rehydration

### ISSUE THREAD

**Issue by sylvaingi** [michalkvasnicak/routex#9]
Right now `createRoutex` discards the router state that could be generated server side. Is it because of some race condition with async routes or something else?

My use case for having the server state rehydrated is that I'd like to use the routes `onEnter` to specify data dependencies for the current route. Ideally this callback would be called only once, since the data the route needs should already be there when the page loads.

**Comment by michalkvasnicak** [comment]
Yes it is discarded because of this https://github.com/michalkvasnicak/routex/blob/master/src/createRoutex.js#L26 and this https://github.com/michalkvasnicak/routex/blob/master/src/createRoutex.js#L44

Thought behind it was that I want to run `onEnter` on the client side too on the same route because code splitting or some async stuff user wants to do.

If you don't want to call data dependencies again on the client side you'll need to use `getState` in `onEnter` and write some conditions.

**Comment by michalkvasnicak** [comment]
For example. You are fetching some articles on the server side `onEnter` from DB. If you want them to be stored, you can dispatch some custom action, to store them to articles store and then resolve onEnter promise so router will know when the transition finished.

**Comment by michalkvasnicak** [comment]
```js
const routes = [{
  path: '/',
  onEnter(currentRoute, nextRoute, router, dispatch, getState) {
    return loadArticlesFromSomewhere().then((articles) => {
       dispatch(storeArticles(articles));
    });
  }
}];
```

**Comment by sylvaingi** [comment]
I'm doing something like this, minus the guard. It works as expected if I add one, thanks for the suggestion!

I only see one reason not to run `onEnter` once, that is if the client somehow ends up calling something else than the server (using an env var or else). Code splitting fall into this case I guess, but I've never really used that feature.

**Comment by michalkvasnicak** [comment]
Yes I know, first release was working like you expect but there was a problem with async routes and code splitting. So I've changed whole codebase. This project is only dev for now, so it'll change in time. 

For example now I am waiting to rackt-history to be published, so I can publish version which depends on it. No more routex BrowserHistory. :)

**Comment by sylvaingi** [comment]
What's the motive for using rack-history? Is it extracted from react-router, which should be battle tested by now?

Otherwise great stuff here! I had a similar vision for a nice router for redux after fighting one day with react-router. I'll make a couple PRs in the upcoming weeks, I'll need stuff like activeClass in <Link/> for what I'm working on.

**Comment by michalkvasnicak** [comment]
Thank you :) I want to use rackt-history because I don't want to implement my own versions of history :)
